crash.types.task: work around missing CONFIG_SCHED_INFO
In Yocto Project 5.8 kernel pycrash produces the following exception:

Loading tasks...crash-python: Failed to open /home/skamensk/oe/20201017/build/vmcore.  No method to retrieve last run from task found.
Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "./build/lib/crash/session.py", line 33, in __init__
    self.kernel.setup_tasks()
  File "./build/lib/crash/kernel.py", line 691, in setup_tasks
    ltask = LinuxTask(task)
  File "./build/lib/crash/types/task.py", line 229, in __init__
    self._init_task_types(task_struct)
  File "./build/lib/crash/types/task.py", line 269, in _init_task_types
    cls._pick_last_run()
  File "./build/lib/crash/types/task.py", line 604, in _pick_last_run
    raise RuntimeError("No method to retrieve last run from task found.")
RuntimeError: No method to retrieve last run from task found.

It turns out that Yocto Project 5.8 kernel does not enable CONFIG_TASKSTATS
and CONFIG_TASK_DELAY_ACCT as result CONFIG_SCHED_INFO is not selected,
as a result this raises the aformentioned exception because struct sched_info
does not have any fields in this case. To work around this
the raising of the RuntimeError was replaced with a print out that states
which CONFIGS must be enabled and cls._get_last was set to a function that
will always return 0.

'pyps -l' functionality is important but there are plenty of other useful
funcationality even if we cannot figure out last run time of task.

Signed-off-by: Alexander Kamensky <alexander.kamensky42@gmail.com>